config/routes.rb
require 'api_constraints'

Polaris::Application.routes.draw do
  resources :recordatorios, only: [:new, :create, :destroy, :edit, :update]

  devise_for :users
  root "static_pages#home"
  devise_scope :user do
    match "signin",       to:   "devise/sessions#new",          via: :get
    match "signout",      to:   "devise/sessions#destroy",      via: :get
    match "registro",     to:   "devise/registrations#new",     via: :get 
    match "editarcuenta", to:   "devise/registrations#edit",    via: :get
    match "borrarcuenta", to:   "devise/registrations#cancel",  via: :get
    match "reestablecer", to:   "devise/passwords#new",         via: :get
  end
  match 'acercade', to: 'static_pages#about', via: :get
  match 'contacto', to: 'static_pages#contact', via: :get
  match 'secret', to: 'static_pages#secret', via: [:get,:post]
  namespace :api, defaults: { format: 'json' } do
    devise_scope :user do
      post 'register' => "registrations#register"
      post 'login' => 'sessions#create'
      delete 'logout' => 'sessions#destroy'
    end
    resources :reminders, only: [:create, :update, :destroy, :index]
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :require_auth_token, only: :secret
  
  def home
  end

  def about
  end

  def contact
  end
  
  def secret
    respond_to do |format|
      format.html
      format.json { render json: {success: true, message: "Secret page" } }
    end
  end
  
  private
  def require_auth_token
    # Check if user is signed in so no token needed
    return if user_signed_in?
    # If the user isn't signed in, look for auth_token param and check against database
    user_token = params[:auth_token].presence
    user = User.find_by_authentication_token user_token.to_s
    sign_in user
    if not user
      redirect_to root_path, alert: "Invalid authentication token"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'Acerca de') %>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contacto') %>

app/views/static_pages/home.html.erb
<div class="main-container">
	<% if user_signed_in? %>
		<%= link_to "Agregar algo que prestaste", new_recordatorio_path, class: "btn btn-large btn-info" %>	
		<% if current_user.recordatorios.any? %>
		<%= render 'shared_views/show' %>
		<% else %>
		<div class="well">
			<p class="hero">Nadie tiene algo tuyo prestado! Felicidades!!</p>
		</div>
		<% end %>
	<% else %>
		<div class="login-btn-container">
				<%= link_to 'Iniciar sesión', signin_path, class: "btn btn-large btn-primary pull-center" %>	
		</div>
	<% end %>
</div>

app/views/static_pages/secret.html.erb
<div class="well">
	<p class="hero">
		Nothing to see here
	</p>
</div>