config/routes.rb
require 'api_constraints'

Polaris::Application.routes.draw do
  resources :recordatorios, only: [:new, :create, :destroy, :edit, :update]

  devise_for :users
  root "static_pages#home"
  devise_scope :user do
    match "signin",       to:   "devise/sessions#new",          via: :get
    match "signout",      to:   "devise/sessions#destroy",      via: :get
    match "registro",     to:   "devise/registrations#new",     via: :get 
    match "editarcuenta", to:   "devise/registrations#edit",    via: :get
    match "borrarcuenta", to:   "devise/registrations#cancel",  via: :get
    match "reestablecer", to:   "devise/passwords#new",         via: :get
  end
  match 'acercade', to: 'static_pages#about', via: :get
  match 'contacto', to: 'static_pages#contact', via: :get
  match 'secret', to: 'static_pages#secret', via: [:get,:post]
  namespace :api, defaults: { format: 'json' } do
    devise_scope :user do
      post 'register' => "registrations#register"
      post 'login' => 'sessions#create'
      delete 'logout' => 'sessions#destroy'
    end
    resources :reminders, only: [:create, :update, :destroy, :index]
  end

end

app/models/recordatorio.rb
class Recordatorio < ActiveRecord::Base
  before_save :set_regresado_to_default
  belongs_to :user
  
  validates :user_id, presence: true
  validates :fecha_prestamo, presence: true
  validates :fecha_entrega, presence: false
  validates :contacto, presence: true, length: { maximum: 100 }
  validates :concepto, presence: true, length: { maximum: 100 }
  validates :detalle, presence: false
  validates :lat, presence: false
  validates :long, presence: false
  
  private
  # If regresado field comes nil => set as false
  def set_regresado_to_default
  end
end

app/controllers/recordatorios_controller.rb
class RecordatoriosController < ApplicationController
  # skip_before_filter :verify_authenticity_token
  before_action :set_recordatorio, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /recordatorios
  # GET /recordatorios.json
  # def index
    # @recordatorios = Recordatorio.all
  # end

  # GET /recordatorios/1
  # GET /recordatorios/1.json
  # def show
  # end

  # GET /recordatorios/new
  def new
    # @recordatorio = Recordatorio.new
    @recordatorio = current_user.recordatorios.build
  end

  # GET /recordatorios/1/edit
  def edit
    if not @recordatorio.user_id.eql? current_user.id
      respond_to do |format|
        format.html do
          flash[:alert] = "No estas autorizado para editar este registro"
          redirect_to root_url
        end
        format.json { render json: {success: false, message: "No estas autorizado para editar este registro"}, status: 422 }
      end
    end
  end

  # POST /recordatorios
  # POST /recordatorios.json
  def create
    @recordatorio = current_user.recordatorios.new(recordatorio_params)

    respond_to do |format|
      if @recordatorio.save
        format.html { redirect_to root_path, notice: 'Creado exitosamente' }
        format.json { render action: 'show', status: :created, location: @recordatorio }
      else
        format.html { render action: 'new' }
        format.json { render json: @recordatorio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recordatorios/1
  # PATCH/PUT /recordatorios/1.json
  def update
    if @recordatorio.user_id.eql? current_user.id
      respond_to do |format|
        if @recordatorio.update(recordatorio_params)
          format.html { redirect_to root_path, notice: 'Editado exitosamente ;)' }
          format.json { render json: {success: true, message: "Editado exitosamente"}, status: 200 }
        else
          format.html { render action: 'edit' }
          format.json { render json: @recordatorio.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to root_path, notice: "No tienes autorizacion para realizar eso :("}
        format.json { render json: {success: false, message: "No tienes autorizacion para realizar eso :("}, status: 422 }
      end
    end
  end

  # DELETE /recordatorios/1
  # DELETE /recordatorios/1.json
  def destroy
    if @recordatorio.user_id.eql? current_user.id
      @recordatorio.destroy
      respond_to do |format|
        format.html { redirect_to root_path }
        format.json { render json: {success: true, message: "Eliminado"}, status: 200 }
      end
    else
      respond_to do |format|
        format.html { redirect_to root_path, notice: "No tienes autorizacion para realizar eso :("}
        format.json { render json: {success: false, message: "No tienes autorizacion para realizar eso :("}, status: 422 }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recordatorio
      @recordatorio = Recordatorio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recordatorio_params
      params.require(:recordatorio).permit(:user_id, :fecha_prestamo, :fecha_entrega, :contacto, :concepto, :detalle, :regresado, :lat, :long)
    end
end

app/helpers/recordatorios_helper.rb
module RecordatoriosHelper
end

app/views/recordatorios/_form.html.erb
<%= form_for(@recordatorio) do |f| %>
  <% if @recordatorio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recordatorio.errors.count, "error") %> prohibieron esta peticion de ser guardada:</h2>

      <ul>
      <% @recordatorio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<%= hidden_field(:recordatorio, :user_id) %>
	<%= hidden_field(:recordatorio, :regresado, options: {checked: false})%>
	<br />
	<div class="field">
		<%= f.label :fecha_prestamo %><br>
		<%= f.date_select :fecha_prestamo %>
	</div>
	<div class="field">
		<%= f.label :fecha_entrega %><br>
		<%= f.date_select :fecha_entrega %>
	</div>
	<div class="field">
		<%= f.label :contacto %><br>
		<%= f.text_field :contacto %>
	</div>
	<div class="field">
		<%= f.label :concepto %><br>
		<%= f.text_field :concepto %>
	</div>
	<div class="field">
		<%= f.label :detalle %><br>
		<%= f.text_field :detalle %>
	</div>
	<div class="actions">
		<% if controller.action_name.to_s.eql? "edit" %>
			<%= f.submit "Editar!", class: "btn btn-large btn-warning" %>
		<% else %>
			<%= f.submit "Agregar!", class: "btn btn-large btn-warning" %>
		<% end %>
	</div>
<% end %>

app/views/recordatorios/edit.html.erb
<div class="well">
	<h1>Editando</h1>

	<%= render 'form' %>
</div>

app/views/recordatorios/index.html.erb
<h1>Listing recordatorios</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Fecha prestamo</th>
      <th>Fecha entrega</th>
      <th>Contacto</th>
      <th>Concepto</th>
      <th>Detalle</th>
      <th>Regresado</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @recordatorios.each do |recordatorio| %>
      <tr>
        <td><%= recordatorio.user_id %></td>
        <td><%= recordatorio.fecha_prestamo %></td>
        <td><%= recordatorio.fecha_entrega %></td>
        <td><%= recordatorio.contacto %></td>
        <td><%= recordatorio.concepto %></td>
        <td><%= recordatorio.detalle %></td>
        <td><%= recordatorio.regresado %></td>
        <td><%= link_to 'Show', recordatorio %></td>
        <td><%= link_to 'Edit', edit_recordatorio_path(recordatorio) %></td>
        <td><%= link_to 'Destroy', recordatorio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recordatorio', new_recordatorio_path %>

app/views/recordatorios/new.html.erb
<div class="well">
	<h1>New recordatorio</h1>

	<%= render 'form' %>

	<!-- <%= link_to 'Back', recordatorios_path %> -->
</div>

app/views/recordatorios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @recordatorio.user_id %>
</p>

<p>
  <strong>Fecha prestamo:</strong>
  <%= @recordatorio.fecha_prestamo %>
</p>

<p>
  <strong>Fecha entrega:</strong>
  <%= @recordatorio.fecha_entrega %>
</p>

<p>
  <strong>Contacto:</strong>
  <%= @recordatorio.contacto %>
</p>

<p>
  <strong>Concepto:</strong>
  <%= @recordatorio.concepto %>
</p>

<p>
  <strong>Detalle:</strong>
  <%= @recordatorio.detalle %>
</p>

<p>
  <strong>Regresado:</strong>
  <%= @recordatorio.regresado %>
</p>

<%= link_to 'Edit', edit_recordatorio_path(@recordatorio) %> |
<%= link_to 'Back', recordatorios_path %>