config/routes.rb
require 'api_constraints'

Polaris::Application.routes.draw do
  resources :recordatorios, only: [:new, :create, :destroy, :edit, :update]

  devise_for :users
  root "static_pages#home"
  devise_scope :user do
    match "signin",       to:   "devise/sessions#new",          via: :get
    match "signout",      to:   "devise/sessions#destroy",      via: :get
    match "registro",     to:   "devise/registrations#new",     via: :get 
    match "editarcuenta", to:   "devise/registrations#edit",    via: :get
    match "borrarcuenta", to:   "devise/registrations#cancel",  via: :get
    match "reestablecer", to:   "devise/passwords#new",         via: :get
  end
  match 'acercade', to: 'static_pages#about', via: :get
  match 'contacto', to: 'static_pages#contact', via: :get
  match 'secret', to: 'static_pages#secret', via: [:get,:post]
  namespace :api, defaults: { format: 'json' } do
    devise_scope :user do
      post 'register' => "registrations#register"
      post 'login' => 'sessions#create'
      delete 'logout' => 'sessions#destroy'
    end
    resources :reminders, only: [:create, :update, :destroy, :index]
  end

end

app/views/layouts/_flash.html.erb
<% if notice||alert %>
	<div class="container-flash">
		<% if notice %>
			<p class="notice"><%= notice %></p>
		<% end %>
		<% if alert %>
			<p class="alert"><%= alert %></p>
		<% end %>
	</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href='#'>Polaris</a>
	</small>
	<nav>
		<ul class="nav pull-right">
			<li><%= link_to "Acerca de",	acercade_path %></li>
			<li><%= link_to "Contacto",		contacto_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="navbar-container">
			<h1 class="center"><%= link_to "Polaris", root_path, class:"no-style"%></h1>
			<% if user_signed_in? %>
				<p class="hero pull-right"><%= link_to "Cerrar sesión", signout_path %></p>
			<% end %>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<%= render 'layouts/flash' %>
	<div class="application-container">
		<%= yield %>
	</div>
	<%= render 'layouts/footer' %>
</body>
</html>